// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"database/sql"
	"encoding/json"
)

type JobReceipt struct {
	ID         int32           `json:"id"`
	JobID      string          `json:"job_id"`
	Status     string          `json:"status"`
	RetryCount int32           `json:"retry_count"`
	Message    string          `json:"message"`
	JobName    string          `json:"job_name"`
	JobContext json.RawMessage `json:"job_context"`
	CreatedAt  int64           `json:"created_at"`
	UpdatedAt  int64           `json:"updated_at"`
}

type Service struct {
	ServiceID                       string         `json:"service_id"`
	JobName                         sql.NullString `json:"job_name"`
	Enabled                         bool           `json:"enabled"`
	RailwayMemoryUpscaleThreshold   float64        `json:"railway_memory_upscale_threshold"`
	RailwayCpuUpscaleThreshold      float64        `json:"railway_cpu_upscale_threshold"`
	RailwayMemoryDownscaleThreshold float64        `json:"railway_memory_downscale_threshold"`
	RailwayCpuDownscaleThreshold    float64        `json:"railway_cpu_downscale_threshold"`
	UpscaleCooldown                 string         `json:"upscale_cooldown"`
	DownscaleCooldown               string         `json:"downscale_cooldown"`
	MinReplicaCount                 int32          `json:"min_replica_count"`
	MaxReplicaCount                 int32          `json:"max_replica_count"`
}
