// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

type IncidentReport struct {
	ID            int32  `json:"id"`
	ServiceID     string `json:"service_id"`
	DeploymentID  string `json:"deployment_id"`
	EnvironmentID string `json:"environment_id"`
	Message       string `json:"message"`
	Timestamp     int64  `json:"timestamp"`
}
