// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"database/sql"
)

type Service struct {
	ServiceID string         `json:"service_id"`
	JobName   sql.NullString `json:"job_name"`
}
