// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"database/sql"
	"time"
)

type FeatureFlag struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Enabled   bool         `json:"enabled"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type FeatureFlagsRule struct {
	FeatureFlagID int32        `json:"feature_flag_id"`
	RuleID        int32        `json:"rule_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type GooseDbVersion struct {
	ID        int32     `json:"id"`
	VersionID int64     `json:"version_id"`
	IsApplied bool      `json:"is_applied"`
	Tstamp    time.Time `json:"tstamp"`
}

type Rule struct {
	ID            int32         `json:"id"`
	FeatureFlagID sql.NullInt32 `json:"feature_flag_id"`
	Field         string        `json:"field"`
	Operator      string        `json:"operator"`
	Value         string        `json:"value"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
}
