name: Docker Build and Push on Push

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME_BASE: ${{ github.repository }} # owner/repo
    SERVICES: configurator autoscale dashboard incident feature-flags scheduler

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push images
              run: echo "Building services..."

    build-images:
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service:
                    [
                        configurator,
                        autoscale,
                        dashboard,
                        incident,
                        feature-flags,
                        scheduler,
                    ]

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Docker metadata for ${{ matrix.service }}
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}/${{ matrix.service }}
                  tags: latest,${{ github.sha }}
                  labels: org.opencontainers.image.source=${{ github.repository }}

            - name: Build and push ${{ matrix.service }} image
              uses: docker/build-push-action@v5
              with:
                  context: ./${{ matrix.service }}
                  file: ./${{ matrix.service }}/Dockerfile.dev
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
